#!name=Bilibili regions
#!desc=Bilibili regions auto switch

[Proxy Group]
📺 Bilibili = select, 🍂 Domestic,🎫 香港, 🎖 台湾, hidden=true

[Rule]
RULE-SET,https://raw.githubusercontent.com/DivineEngine/Profiles/master/Surge/Ruleset/StreamingMedia/StreamingSE.list,📺 Bilibili

[Script]
Bili Region = type=http-response,pattern=^https:\/\/ap(p|i)\.bili(bili|api)\.(com|net)\/(pgc\/view\/v\d\/app\/season|x\/v\d\/search\/defaultwords)\?access_key,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/0ox/MyProfile/master/Surge/JavaScript/Regions.js
Bili Search = type=http-request,pattern=^https:\/\/ap(p|i)\.bili(bili|api)\.(com|net)\/x\/v\d\/search(\/type)?\?.+?%20(%E6%B8%AF|%E5%8F%B0|%E4%B8%AD)&,script-path=https://raw.githubusercontent.com/0ox/MyProfile/master/Surge/JavaScript/Regions.js

[MITM]
hostname = %APPEND% ap?.bilibili.com, ap?.biliapi.net
