#!name=HistoryPrice
#!desc=Display jd/tb historical price
#!system=ios

[Script]

[Script]
淘宝比价 = type=http-response,pattern=^https?://api\.m\.jd\.com/client\.action\?functionId=(wareBusiness|serverConfig|basicConfig),requires-body=1,max-size=0,script-path=https://service.2ti.st/QuanX/Script/jd_tb_price/main.js,script-update-interval=0
京东比价 = requires-body=1,script-path=https://service.2ti.st/QuanX/Script/jd_tb_price/main.js,type=http-request,pattern=^http://.+/amdc/mobileDispatch
京东比价 = type=http-response,pattern=^https?://trade-acs\.m\.taobao\.com/gw/mtop\.taobao\.detail\.getdetail,requires-body=1,max-size=0,script-path=https://service.2ti.st/QuanX/Script/jd_tb_price/main.js,script-update-interval=0

[MITM]
hostname = %INSERT% %APPEND% api.m.jd.com, trade-acs.m.taobao.com
