#!name=Ximalaya
#!desc= Ximalaya AD remove.

[Rule]
URL-REGEX,^http:\/\/adse\.ximalaya\.com\/(ting|adx)(?!preSale),REJECT 
DOMAIN,gslbali.ximalaya.com,REJECT
DOMAIN,gslbtx.ximalaya.com,REJECT

[Script]
喜马拉雅 = type=http-response,pattern=^https?:\/\/mobile\.ximalaya\.com\/(discovery-feed|category|mobile-user)\/v\d\/(mix|category|homePage),requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/ddgksf2013/Cuttlefish/master/Script/xmlyad.js,script-update-interval=0

[MITM]
hostname = %APPEND% mobile.ximalaya.com
